- name: Microsoft Teams (Generic)
  uses: aliencube/microsoft-teams-actions@v0.8.0
  with:
    # Incoming webhook URI to Microsoft Teams
    webhook_uri: 
    # Message title
    title: # optional, default is 
    # Message summary
    summary: # optional, default is 
    # Message text
    text: # optional, default is 
    # Message theme color
    theme_color: # optional, default is 
    # JSON array for message sections
    sections: # optional, default is 
    # JSON array for message actions
    actions: # optional, default is 
